# docker compose -p exchange-info-bot up -d

services:

  telegram-bot:
    build: .
    image: my-bot:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/exchange-info-bot-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      BOT_USERNAME: TheExchangeInfoBot
      BOT_TOKEN: 6126015745:AAGNig_TMslHTAxx68xb_1nfdIMPDhUYwj8
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:17
    environment:
      POSTGRES_DB: exchange-info-bot-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "10008:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: